# Generated by Django 3.1.6 on 2021-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockinfo',
            fields=[
                ('branch_code', models.CharField(max_length=15)),
                ('imei', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
