# Generated by Django 3.1.6 on 2021-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
