# Generated by Django 3.1.6 on 2021-03-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0003_auto_20210304_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
