# Generated by Django 3.1.6 on 2021-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=200)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
