# Generated by Django 3.1.6 on 2021-02-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=15)),
                ('franchise_plane', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('password', models.BigIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_number', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('shop_add', models.CharField(max_length=250)),
                ('home_add', models.CharField(max_length=250)),
                ('aadhaar_number', models.BigIntegerField()),
                ('pan_number', models.CharField(max_length=20)),
            ],
        ),
    ]
