# Generated by Django 3.1.6 on 2021-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='franchise_plane',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
