# Generated by Django 3.1.6 on 2021-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
