# Generated by Django 3.1.6 on 2021-03-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_mobilestock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mobilestock',
        ),
    ]
