# Generated by Django 3.1.6 on 2021-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20210304_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='customer_add',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
