# Generated by Django 3.1.6 on 2021-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_sell_customer_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='dp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
