# Generated by Django 3.1.6 on 2021-03-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_sell_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='emi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sell',
            name='imei',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sell',
            name='loan_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
