# Generated by Django 3.1.6 on 2021-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ledgers',
            fields=[
                ('branch_code', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=30)),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('credit', models.BigIntegerField()),
                ('debit', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
