# Generated by Django 3.1.6 on 2021-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='debth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=15)),
                ('debth', models.BigIntegerField()),
            ],
        ),
    ]
